### PR TITLE
Ghpages update

### PR DESCRIPTION
**Pull request by lucakiebel**
### What did you fix? (provide a description or issue closes statement)

updated README and test page of github pages branch to that of master branch

---

### Reproduction steps
N/A

---

### Evidence/screenshot/link to line
N/A

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[No]**
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**

### CODE REVIEW

**Comment by TobiTenno** [comment]
so, is there any way we could possibly automate this so it's not so problematic? we've done automation before with jsdoc, but i'm not 100% on what we'd need to do to template these in the main branches to let it get automated in the gh-pages branch

**Comment by lucakiebel** [comment]
We would essentially have to copy over the README.md and test/test.html into tests/test.html from master to gh-pages, 

Could we use [this](https://github.com/peaceiris/actions-gh-pages)?

**Comment by TobiTenno** [comment]
I think so, we'd just need to have the template someplace, unless the Jekyll config is in the workflow. Go for it, and we can test it out!

**Comment by TobiTenno** [comment]
I'll approve this and we can look at automating it separately

**Review by TobiTenno — APPROVED** [review]

**Pull request merged**
